import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { logout } from "thin-backend";
import { useCurrentUser } from "thin-backend-react";

import { query } from "thin-backend";
import { useQuery } from "thin-backend-react";
import { createRecord, getCurrentUserId } from "thin-backend";

function NewTodoButton() {
  function addTodo(event) {
    const value = window.prompt("Enter a title:") || "";
    console.log("value", value);
    createRecord("todos", {
      title: value,
      userId: getCurrentUserId(),
    });
  }

  return <button onClick={addTodo}>Add Todo</button>;
}

function TodoList() {
  const todos = useQuery(query("todos").orderByDesc("createdAt"));

  if (todos === null) {
    return <div>Loading ...</div>;
  }

  return (
    <div>
      {todos
        .sort((a, b) => a.created_at > b.created_at)
        .map((todo, id) => (
          <div key={id}>{todo.title}</div>
        ))}
    </div>
  );
}

function UserStatus() {
  // Use the `useCurrentUser()` react hook to access the current logged in user
  const user = useCurrentUser();

  return (
    <div>
      {user?.email}

      <button onClick={logout}>Logout</button>
    </div>
  );
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <UserStatus />
        <TodoList />
        <NewTodoButton />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
